input_root: /mnt/nvme_user/baoquan/Label_Data/images_folder
output_root: /mnt/nvme_user/baoquan/Label_Data/benchmark-export/page_level

random_seed: 42

normalization:
  dark_percentile: 1.0
  light_percentile: 99.5
  threshold_method: equal_image_weighted_otsu
